// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserGroup is the predicate function for usergroup builders.
type UserGroup func(*sql.Selector)

// UserLog is the predicate function for userlog builders.
type UserLog func(*sql.Selector)
